routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/','print_forms.chem');
// Route::redirect('/','login');
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('test',function(){
	return response()->json(['test'=>'test']);	
});

Auth::routes();
Route::resource('information','BasicInformationController')->except(['delete']);
Route::name('vitalsign.')->prefix('vitalsign/')->group(function(){
    Route::get('/','VitalSignController@index')->name('index');
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});
Route::name('eyesight.')->prefix('eyesight/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::name('psychology.')->prefix('psychology/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/information/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-primary mt-4 ">
	<div class="card-header">
	    Patient Information
	    <a href="{{ route('information.index') }}" class="btn btn-info btn-sm float-right">Back</a>
    </div>
	<div class="card-body">
		<form class="ml-3 mr-3"  method="POST" action="{{ route('information.store') }}">
			{{ csrf_field() }}
			@include('shared.alerts')
			<div class="row mt-3">
				<div class="form-group col-12 col-sm-4">
				    <label class="form-control-label" for="lastname">Lastname:</label>
				    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ old('lastname') }}" placeholder="Dela Cruz">
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="firstname">Firstname:</label>
				    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ old('firstname') }}" placeholder="Juan"> 
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="middlename">Middlename:</label>
				    <input type="text" class="form-control" id="middlename" name="middlename" value="{{ old('middlename') }}" placeholder="Basmayor">
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12">
					<label class="form-control-label" for="mailingaddress">Mailing Address:</label>
					<input type="text" class="form-control" id="mailingaddress" name="mailingaddress" value="{{ old('mailingaddress') }}" placeholder="Vista Verde Executive Village, Cainta Rizal">
				</div>
			</div>	
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="passport">Passport:</label>
				    <input type="text" class="form-control" id="passport" name="passport" value="{{ old('passport') }}"  placeholder="E03BX44">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="gender">Gender:</label>
				    <select id="gender" name="gender" class="form-control">
				    	<option value="1" @if(old('gender') == 1) selected @endif>Male</option>
				    	<option value="2" @if(old('gender') == 2) selected @endif>Female</option>
				    </select>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
				    <label class="form-control-label" for="birthday">Birthday:</label> 
				    <input type="date" class="form-control" id="birthday" name="birthday" value="{{ old('birthday') }}" placeholder="dd/mm/yy">
				</div>
				<div class="form-group col-12 col-sm12 col-lg-5">
				    <label class="form-control-label" for="placeofbirth">Place of birth:</label> 
				    <input type="text" class="form-control" id="placeofbirth" name="placeofbirth" value="{{ old('placeofbirth') }}" placeholder="Meycauayan, Bulacan">
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
					<label class="form-control-label" class="form-control">Civil Status:</label>
					<select id="civilstatus" name="civilstatus" class="form-control">
						<option value="1" @if(old('civilstatus') == 1) selected @endif>Single</option>
						<option value="2" @if(old('civilstatus') == 2) selected @endif>Married</option>
						<option value="3" @if(old('civilstatus') == 3) selected @endif>Divorced</option>
						<option value="4" @if(old('civilstatus') == 4) selected @endif>Widow</option>
					</select>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-4">
					<label class="form-control-label" for="phonenum">Cellphone Number:</label> 
				    <input type="text" class="form-control" id="phonenum" name="phonenum" value="{{ old('phonenum') }}" placeholder="">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="occupation">Occupation:</label> 
				    <input type="text" class="form-control" id="occupation" name="occupation" value="{{ old('occupation') }}" placeholder="HR Manager">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="destination">Destination:</label> 
				    <select id="destination" name="destination" class="form-control">
						<option value="LOCAL" @if(old('destination') == "LOCAL") selected @endif>LOCAL</option>
						<option value="FOREIGN" @if(old('destination') == "FOREIGN") selected @endif>FOREIGN</option>
					</select>
				</div>
			</div>
			<hr>
			<div class="row">
				@foreach($diseases as $disease)
					<div class="col-12 col-sm-7 col-md-6">
						<input type="checkbox"  id="{{ $disease->id }}"  name="disease[{{$disease->id}}]" value="{{ $disease->id }}" {{ in_array($disease->id,old('disease',[])) ?'checked':'' }} >
						<label for="{{ $disease->id }}" class="control-label">{{ $disease->disease }}</label>
					</div>
				@endforeach
			</div>
			<hr>
			<div class="form-group row">
		      <div class="col-sm-10">
		        <button type="submit" class="btn btn-primary">Save</button>
		      </div>
		    </div>
		</form>
	</div>
</div>
</div>
@endsection

resources/views/information/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card border-primary mt-4 ">
	<div class="card-header">Update Patient {{ $patient->id }}
	<a href="{{ route('information.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a></div>
	<div class="card-body">
		<form class="ml-3 mr-3"  method="POST" action="{{ route('information.update',['id' => $patient->id]) }}">
			{{ csrf_field() }}
			{{ method_field('PATCH') }}
			@include('shared.alerts')
			<div class="row mt-3">
				<div class="form-group col-12 col-sm-4">
				    <label class="form-control-label" for="lastname">Lastname:</label>
				    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ $patient->lastname }}" >
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="firstname">Firstname:</label>
				    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ $patient->firstname }}"> 
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="middlename">Middlename:</label>
				    <input type="text" class="form-control" id="middlename" name="middlename" value="{{ $patient->middlename }}">
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12">
					<label class="form-control-label" for="mailingaddress">Mailing Address:</label>
					<input type="text" class="form-control" id="mailingaddress" name="mailingaddress" value="{{ $patient->mailingaddress }}" >
				</div>
			</div>	
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="passport">Passport:</label>
				    <input type="text" class="form-control" id="passport" name="passport" value="{{ $patient->passport }}">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="gender">Gender:</label>
				    <select id="gender" name="gender" class="form-control">
				    	<option value="1" @if($patient->gender == 1) selected @endif>Male</option>
				    	<option value="2" @if($patient->gender  == 2) selected @endif>Female</option>
				    </select>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
				    <label class="form-control-label" for="birthday">Birthday:</label> 
				    <input type="date" class="form-control" id="birthday" name="birthday" value="{{ $patient->birthday }}" placeholder="dd/mm/yy">
				</div>
				<div class="form-group col-12 col-sm12 col-lg-5">
				    <label class="form-control-label" for="placeofbirth">Place of birth:</label> 
				    <input type="text" class="form-control" id="placeofbirth" name="placeofbirth" value="{{ $patient->placeofbirth }}">
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
					<label class="form-control-label" class="form-control">Civil Status:</label>
					<select id="civilstatus" name="civilstatus" class="form-control">
						<option value="1" @if($patient->civilstatus == "Single") selected @endif>Single</option>
						<option value="2" @if($patient->civilstatus == "Married") selected @endif>Married</option>
						<option value="3" @if($patient->civilstatus == "Divorced") selected @endif>Divorced</option>
						<option value="4" @if($patient->civilstatus == "Widow") selected @endif>Widow</option>
					</select>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-4">
					<label class="form-control-label" for="phonenum">Cellphone Number:</label> 
				    <input type="text" class="form-control" id="phonenum" name="phonenum" value="{{ $patient->telnumber }}" placeholder="">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="occupation">Occupation:</label> 
				    <input type="text" class="form-control" id="occupation" name="occupation" value="{{ $patient->occupation }}" placeholder="HR Manager">
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="destination">Destination:</label> 
				    <select id="destination" name="destination" class="form-control">
						<option value="LOCAL" @if($patient->destination== "LOCAL") selected @endif>LOCAL</option>
						<option value="FOREIGN" @if($patient->destination == "FOREIGN") selected @endif>FOREIGN</option>
					</select>
					
				</div>
			</div>
			<hr>
			<div class="row">
				@foreach($diseases as $disease)
					<div class="col-12 col-sm-7 col-md-6">
						<input type="checkbox"  id="{{ $disease->id }}"  name="disease[{{$disease->id}}]" value="{{ $disease->id }}" {{ in_array($disease->id,explode(',',$patient->history)) ?'checked':'' }} >
						<label for="{{ $disease->id }}" class="control-label">{{ $disease->disease }}</label>
					</div>
				@endforeach
			</div>
			<hr>
			<div class="form-group row">
		      <div class="col-sm-10">
		        <button type="submit" class="btn btn-primary">Save</button>
		      </div>
		    </div>
		</form>
	</div>
</div>
</div>
@endsection

resources/views/information/index.blade.php
@extends('layouts.app')
@section('content') 
<div class="container mt-4">
    <div class="card card-info">
        <div class="card-header">
             Patients
             <a href="{{ route('information.create') }}" class="btn btn-sm btn-info float-right">New Record</a>
        </div>
        <div class="card-body">
            <table class="table table-light table-bordered" id="myTable">
                <thead>
                    <th>ID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Date Created</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($patients as $patient)
                    <tr>
                        <td>{{ $patient->id }}</td>
                        <td>{{ $patient->firstname }}</td>
                        <td>{{ $patient->lastname }}</td>
                        <td>{{ $patient->created_at }}</td>
                        <td>
                            <a href="{{ route('information.show',['id' => $patient->id]) }}" class="btn btn-sm btn-info text-light">View</a>
                            <a href="{{ route('information.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-primary text-light">Edit</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            A Total Patients of {{ $patients->count() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
    $('#myTable').DataTable();
</script>
@endpush
@push('styles')
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

resources/views/information/view.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12 col-xs-12 col-12 mx-auto">
			<div class="card border-dark mt-4">
			  <div class="card-header">Patient
			  	<a href="{{ route('information.index') }}" class="btn btn-primary btn-sm mr-auto float-right">
					Back
				</a>
				</div>
				<div class="card-body">
					@include('shared.alerts')
					<div class="row mt-3">
				<div class="form-group col-12 col-sm-4">
				    <label class="form-control-label" for="lastname">Lastname:</label>
				    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ $patient->lastname }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="firstname">Firstname:</label>
				    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ $patient->firstname }}" readonly> 
				</div>
				<div class="form-group col-12 col-sm-4">
					<label class="form-control-label" for="middlename">Middlename:</label>
				    <input type="text" class="form-control" id="middlename" name="middlename" value="{{ $patient->middlename }}" readonly>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12">
					<label class="form-control-label" for="mailingaddress">Mailing Address:</label>
					<input type="text" class="form-control" id="mailingaddress" name="mailingaddress" value="{{ $patient->mailingaddress }}" readonly>
				</div>
			</div>	
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="passport">Passport:</label>
				    <input type="text" class="form-control" id="passport" name="passport" value="{{ $patient->passport }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-2">
				    <label class="form-control-label" for="gender">Gender:</label>
				    <select id="gender" name="gender" readonly class="form-control">
				    	<option value="1" @if($patient->gender == 1) selected @endif>Male</option>
				    	<option value="2" @if($patient->gender == 2) selected @endif>Female</option>
				    </select>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
				    <label class="form-control-label" for="birthday">Birthday:</label> 
				    <input type="date" class="form-control" id="birthday" name="birthday" value="{{ $patient->birthday }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-1">
				    <label class="form-control-label" for="birthday">Age:</label> 
				    <input type="text" class="form-control" id="birthday" name="birthday" value="{{ $patient->age }}" readonly>
				</div>
				<div class="form-group col-12 col-sm12 col-lg-4">
				    <label class="form-control-label" for="placeofbirth">Place of birth:</label> 
				    <input type="text" class="form-control" id="placeofbirth" name="placeofbirth" value="{{ $patient->placeofbirth }}" readonly>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-12 col-sm-12 col-lg-2">
					<label class="form-control-label" class="form-control">Civil Status:</label>
					 <input type="text" class="form-control"  value="{{ $patient->civilstatus }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-4">
					<label class="form-control-label" for="phonenum">Cellphone Number:</label> 
				    <input type="text" class="form-control" id="phonenum" name="phonenum" value="{{ $patient->telnumber }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="occupation">Occupation:</label> 
				    <input type="text" class="form-control" id="occupation" name="occupation" value="{{ $patient->occupation }}" readonly>
				</div>
				<div class="form-group col-12 col-sm-12 col-lg-3">
					<label class="form-control-label" for="destination">Destination:</label> 
				    <input type="text" class="form-control" id="destination" name="destination" value="{{ $patient->destination }}" readonly>
				</div>
			</div>
			<hr>
			<div class="row">
				@foreach($diseases as $disease)
					<div class="col-12 col-sm-7 col-md-6">
						<input disabled type="checkbox"  id="{{ $disease->id }}"  name="disease[{{$disease->id}}]" value="{{ $disease->id }}" {{ in_array($disease->id,explode(",",$patient->history)) ?'checked':'' }} >
						<label for="{{ $disease->id }}" class="control-label">{{ $disease->disease }}</label>
					</div>
				@endforeach
			</div>
			<!--<div class="row">-->
			<!--	<a href="{{ route('information.edit',['id' => $patient->id]) }}" class="btn btn-info ml-3 mt-3 btn-sm">Edit</a>-->
			<!--</div>-->
		</div>
	</div>
</div>
@endsection