routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/','print_forms.chem');
// Route::redirect('/','login');
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('test',function(){
	return response()->json(['test'=>'test']);	
});

Auth::routes();
Route::resource('information','BasicInformationController')->except(['delete']);
Route::name('vitalsign.')->prefix('vitalsign/')->group(function(){
    Route::get('/','VitalSignController@index')->name('index');
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});
Route::name('eyesight.')->prefix('eyesight/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::name('psychology.')->prefix('psychology/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/EyeSight.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class EyeSight extends Model
{
    //
}

app/Http/Controllers/EyeSightController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\BasicInformation;
use App\Models\ActivityLog;
use App\Models\EyeSight;
use Auth;
class EyeSightController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('eyesight.index')
                ->with(['patients' => BasicInformation::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('eyesight.create')
                ->with([
                    'id' => $id,
                    'patient' => BasicInformation::find($id)
                ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id)
    {
        $request->validate([
            'uc_fv_od' => 'required|integer',
            'uc_fv_os' => 'required|integer',
            'c_fv_od' => 'required|integer',
            'c_fv_os' => 'required|integer',
            'uc_nv_od' => 'required|integer',
            'uc_nv_os' => 'required|integer',
            'c_nv_od' => 'required|integer',
            'c_nv_os' => 'required|integer',
            'optical' => 'required|boolean',
            'colorvision' => 'required|boolean',
            'ad' => 'required|integer',
            'as' => 'required|integer'
        ]);
        $patient = new EyeSight;
        $patient->information_id = $id;
        $patient->uncorrected_fv_od = $request->uc_fv_od;
        $patient->unccorected_fv_os = $request->uc_fv_os;
        $patient->uncorrected_nv_od = $request->uc_nv_od;
        $patient->unccorected_nv_os = $request->uc_nv_os;
        $patient->corrected_fv_od = $request->c_fv_od;
        $patient->corrected_fv_os = $request->c_fv_os;
        $patient->corrected_nv_od = $request->c_nv_od;
        $patient->corrected_nv_os = $request->c_nv_os;
        $patient->optical = $request->optical;
        $patient->colorvision = $request->colorvision;
        $patient->as = $request->as;
        $patient->ad = $request->ad;
        $patient->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Created a vital sign information for patient '.$id]);
        return redirect()->route('eyesight.index')->with('status','Successfully added a vital sign to patient '.$id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $patient = EyeSight::where('information_id',$id)->first();

        return view('eyesight.edit')
                ->with(['vitals' => $patient]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            
            'uc_fv_od' => 'required|integer',
            'uc_fv_os' => 'required|integer',
            'c_fv_od' => 'required|integer',
            'c_fv_os' => 'required|integer',
            'uc_nv_od' => 'required|integer',
            'uc_nv_os' => 'required|integer',
            'c_nv_od' => 'required|integer',
            'c_nv_os' => 'required|integer',
            'optical' => 'required|boolean',
            'colorvision' => 'required|boolean',
            'ad' => 'required|integer',
            'as' => 'required|integer'
        ]);
        $vitalsign = EyeSight::find($id);
        $vitalsign->uncorrected_fv_od = $request->uc_fv_od;
        $vitalsign->unccorected_fv_os = $request->uc_fv_os;
        $vitalsign->uncorrected_nv_od = $request->uc_nv_od;
        $vitalsign->unccorected_nv_os = $request->uc_nv_os;
        $vitalsign->corrected_fv_od = $request->c_fv_od;
        $vitalsign->corrected_fv_os = $request->c_fv_os;
        $vitalsign->corrected_nv_od = $request->c_nv_od;
        $vitalsign->corrected_nv_os = $request->c_nv_os;
        $vitalsign->optical = $request->optical;
        $vitalsign->colorvision = $request->colorvision;
        $vitalsign->as = $request->as;
        $vitalsign->ad = $request->ad;
        $vitalsign->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Updated a vital sign information for patient '.$id]);
        return redirect()->route('eyesight.index')->with('status','Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/eyesight/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-info mt-3">
		<div class="card-header">Eye Sight - Patient {{ $patient->firstname }} {{ $patient->lastname }}</div>
		<div class="card-body">
			<form method="POST" action="{{ route('eyesight.store',['id' => $id]) }}">
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_od">Uncorrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="uc_fv_od" name="uc_fv_od" value="{{ old('uc_fv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_os">Uncorrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="uc_fv_os" name="uc_fv_os" value="{{ old('uc_fv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_od">Corrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="c_fv_od" name="c_fv_od" value="{{ old('c_fv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_os">Corrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="c_fv_os" name="c_fv_os" value="{{ old('c_fv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_od">Uncorrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="uc_nv_od" name="uc_nv_od" value="{{ old('uc_nv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_os">Uncorrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="uc_nv_os" name="uc_nv_os" value="{{ old('uc_nv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_od">Corrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="c_nv_od" name="c_nv_od" value="{{ old('c_nv_od') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_os">Corrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="c_nv_os" name="c_nv_os" value="{{ old('c_nv_os') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="optical">Optical:</label>
					   	<select class="form-control" name="optical" id="optical">
					   		<option value="0">For Opto Clearance</option>
					   		<option value="1">Cleared</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="colorvision">Color Vision:</label>
					    <select class="form-control" name="colorvision" id="colorvision">
					   		<option value="0">Defective</option>
					   		<option value="1">Adequate</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ad">Hearing AD:</label>
					    <input type="text" class="form-control" id="ad" name="ad" value="{{ old('ad') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="as">Hearing AS:</label>
					    <input type="text" class="form-control" id="as" name="as" value="{{ old('as') }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/eyesight/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
		<div class="card card-info mt-3">
		<div class="card-header">
		    Eye Sight of Patient {{ $vitals->information_id }}
		    <a href="{{ route('eyesight.index') }}" class="btn btn-sm btn-info float-right">Back</a>
		    </div>
		<div class="card-body">
			<form method="POST" action="{{ route('eyesight.update',['id' => $vitals->id]) }}">

				{{csrf_field()}} {{ method_field('patch') }}
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_od">Uncorrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="uc_fv_od" name="uc_fv_od" value="{{ $vitals->uncorrected_fv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_fv_os">Uncorrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="uc_fv_os" name="uc_fv_os" value="{{ $vitals->unccorected_fv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_od">Corrected Far Vision OD:</label>
					    <input type="text" class="form-control" id="c_fv_od" name="c_fv_od" value="{{ $vitals->corrected_fv_od }}">
					</div>
					{{-- {{ dd($vitals)}} --}}
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_fv_os">Corrected Far Vision OS:</label>
					    <input type="text" class="form-control" id="c_fv_os" name="c_fv_os" value="{{ $vitals->corrected_fv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_od">Uncorrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="uc_nv_od" name="uc_nv_od" value="{{ $vitals->uncorrected_nv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="uc_nv_os">Uncorrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="uc_nv_os" name="uc_nv_os" value="{{ $vitals->unccorected_nv_os }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_od">Corrected Near Vision OD:</label>
					    <input type="text" class="form-control" id="c_nv_od" name="c_nv_od" value="{{ $vitals->corrected_nv_od }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="c_nv_os">Corrected Near Vision OS:</label>
					    <input type="text" class="form-control" id="c_nv_os" name="c_nv_os" value="{{ $vitals->corrected_nv_os}}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="optical">Optical:</label>
					   	<select class="form-control" name="optical" id="optical">
					   		<option value="0" @if($vitals->optical == 0) selected @endif>For Opto Clearance</option>
					   		<option value="1" @if($vitals->optical == 1) selected @endif>Cleared</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="colorvision">Color Vision:</label>
					    <select class="form-control" name="colorvision" id="colorvision">
					   		<option value="0" @if($vitals->colorvision == 0) selected @endif>Defective</option>
					   		<option value="1" @if($vitals->colorvision == 1) selected @endif>>Adequate</option>
					   	</select>
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ad">Hearing AD:</label>
					    <input type="text" class="form-control" id="ad" name="ad" value="{{ $vitals->ad }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="as">Hearing AS:</label>
					    <input type="text" class="form-control" id="as" name="as" value="{{ $vitals->as }}">
					</div>
				</div>
				<div class="row">
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
						
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/eyesight/index.blade.php
@extends('layouts.app')
@section('content') 
<div class="container mt-4">
    <div class="card card-info">
        <div class="card-header">
             Patients
        </div>
        <div class="card-body">
            @include('shared.alerts')
            <table class="table table-light table-bordered" id="myTable">
                <thead>
                    <th>ID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Date Created</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($patients as $patient)
                    <tr>
                        <td>{{ $patient->id }}</td>
                        <td>{{ $patient->firstname }}</td>
                        <td>{{ $patient->lastname }}</td>
                        <td>{{ $patient->created_at }}</td>
                        <td>
                            @if($patient->eyesight->isEmpty())
                            <a href="{{ route('eyesight.create',['id' => $patient->id]) }}" class="btn btn-sm btn-primary">New Record</a>
                            @else
                            <a href="{{ route('eyesight.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-primary text-light">Edit</a>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            A Total Patients of {{ $patients->count() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
    $('#myTable').DataTable();
</script>
@endpush
@push('styles')
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush