routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/','print_forms.chem');
// Route::redirect('/','login');
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('test',function(){
	return response()->json(['test'=>'test']);	
});

Auth::routes();
Route::resource('information','BasicInformationController')->except(['delete']);
Route::name('vitalsign.')->prefix('vitalsign/')->group(function(){
    Route::get('/','VitalSignController@index')->name('index');
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});
Route::name('eyesight.')->prefix('eyesight/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::name('psychology.')->prefix('psychology/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/VitalSign.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class VitalSign extends Model
{
    public function patient()
    {
        return $this->belongsTo('App\Models\BasicInformation','information_id','id');
    }
}

app/Http/Controllers/VitalSignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\VitalSign;
use App\Models\BasicInformation;
use App\Models\ActivityLog;
use Auth;                                                                                                                    
class VitalSignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('vitalsign.index')
                ->with(['patients' => BasicInformation::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $patient = BasicInformation::find($id);
        return view('vitalsign.create')
                ->with([
                    'id' => $id,
                    'patient' => $patient
                    ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id)
    {
        $request->validate([
            'height' => 'required',
            'weight' => 'required',
            'bp'     => 'required',
            'pulse' => 'required',
            'respiration' => 'required',
            'bmi' => 'required',
            'ppd' => 'required',
            'mmr' => 'required',
            'bodybuilt' => 'required',
            'lmp' => 'nullable',
            'lsc' => 'nullable',
            'method' => 'nullable',
        ]);
        $patient = new Vitalsign;
        $patient->information_id = $id;
        $patient->height = $request->height;
        $patient->weight = $request->weight;
        $patient->bp = $request->bp;
        $patient->pulse = $request->pulse;
        $patient->respiration = $request->respiration;
        $patient->bmi = $request->bmi;
        $patient->ppd = $request->ppd;
        $patient->lmp = $request->lmp;
        $patient->lsc = $request->lsc;
        $patient->bodybuilt = $request->bodybuilt;
        $patient->mmr = $request->mmr;
        $patient->method = $request->method;
        $patient->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Created a vital sign information for patient '.$id]);
        return redirect()->route('vitalsign.index')->with('status','Successfully added a vital sign to patient '.$id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vitalsign = Vitalsign::where('information_id',$id)->first();
        $information = BasicInformation::find($vitalsign->information_id);
        return view('vitalsign.edit')
                ->with([
                    'vitals' => $vitalsign,
                    'patient' => $information
                ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
            'height' => 'required',
            'weight' => 'required',
            'bp'     => 'required',
            'pulse' => 'required',
            'respiration' => 'required',
            'bmi' => 'required',
            'ppd' => 'required',
            'mmr' => 'required',
            'bodybuilt' => 'required',
            'lmp' => 'nullable',
            'lsc' => 'nullable',
            'method' => 'nullable',
        ]);
        $patient = VitalSign::find($id);
        $patient->information_id = $id;
        $patient->height = $request->height;
        $patient->weight = $request->weight;
        $patient->bp = $request->bp;
        $patient->pulse = $request->pulse;
        $patient->respiration = $request->respiration;
        $patient->bmi = $request->bmi;
        $patient->ppd = $request->ppd;
        $patient->lmp = $request->lmp;
        $patient->lsc = $request->lsc;
        $patient->bodybuilt = $request->bodybuilt;
        $patient->mmr = $request->mmr;
        $patient->method = $request->method;
        $patient->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Updated a vital sign information for patient '.$id]);
        return redirect()->route('vitalsign.index')->with('status','Successfully updated a vital sign to patient '.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/vitalsign/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-info mt-3">
		<div class="card-header">Vital Sign - {{ $patient->firstname }} {{ $patient->lastname }}</div>
		<div class="card-body">
			<form method="POST" action="{{ route('vitalsign.store',['id' => $id]) }}">
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="height">Height:</label>
					    <input type="text" class="form-control" id="height" name="height" value="{{ old('height') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="weight">Weight:</label>
					    <input type="text" class="form-control" id="weight" name="weight" value="{{ old('weight') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="bp">BP:</label>
					    <input type="text" class="form-control" id="bp" name="bp" value="{{ old('bp') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">Pulse:</label>
					    <input type="text" class="form-control" id="pulse" name="pulse" value="{{ old('pulse') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="respiration">Respiration:</label>
					    <input type="text" class="form-control" id="respiration" name="respiration" value="{{ old('respiration') }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">BMI:</label>
					    <input type="text" class="form-control" id="bmi" name="bmi" value="{{ old('bmi') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ppd">PPD:</label>
					    <input type="text" class="form-control" id="ppd" name="ppd" value="{{ old('ppd') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="mmr">MMR:</label>
					    <input type="text" class="form-control" id="mmr" name="mmr" value="{{ old('mmr') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="bodybuilt">Body Built:</label>
					    <input type="text" class="form-control" id="bodybuilt" name="bodybuilt" value="{{ old('bodybuilt') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lmp">L.M.P:</label>
					    <input type="text" class="form-control" id="lmp" name="lmp" value="{{ old('lmp') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lsc">L.S.C:</label>
					    <input type="text" class="form-control" id="lsc" name="lsc" value="{{ old('lsc') }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="method">Method:</label>
					    <input type="text" class="form-control" id="method" name="method" value="{{ old('method') }}">
					</div>
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/vitalsign/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
		<div class="card card-info mt-3">
		<div class="card-header">Updating Vital Sign - {{ $patient->firstname }} {{ $patient->lastname }}</div>
		<div class="card-body">
			<form method="POST" action="{{ route('vitalsign.update',['id' => $vitals->id]) }}">

				{{csrf_field()}} {{ method_field('patch') }}
				@include('shared.alerts')
				<div class="row">
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="height">Height:</label>
					    <input type="text" class="form-control" id="height" name="height" value="{{ $vitals->height }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="weight">Weight:</label>
					    <input type="text" class="form-control" id="weight" name="weight" value="{{ $vitals->weight }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="bp">BP:</label>
					    <input type="text" class="form-control" id="bp" name="bp" value="{{ $vitals->bp }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">Pulse:</label>
					    <input type="text" class="form-control" id="pulse" name="pulse" value="{{ $vitals->pulse }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="respiration">Respiration:</label>
					    <input type="text" class="form-control" id="respiration" name="respiration" value="{{ $vitals->respiration }}">
					</div>
					<div class="form-group col-12 col-sm-3">
					    <label class="form-control-label" for="pulse">BMI:</label>
					    <input type="text" class="form-control" id="bmi" name="bmi" value="{{ $vitals->bmi }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="ppd">PPD:</label>
					    <input type="text" class="form-control" id="ppd" name="ppd" value="{{ $vitals->ppd }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="mmr">MMR:</label>
					    <input type="text" class="form-control" id="mmr" name="mmr" value="{{ $vitals->mmr }}">
					</div>
					<div class="form-group col-12 col-sm-2">
					    <label class="form-control-label" for="bodybuilt">Body Built:</label>
					    <input type="text" class="form-control" id="bodybuilt" name="bodybuilt" value="{{ $vitals->bodybuilt }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lmp">L.M.P:</label>
					    <input type="text" class="form-control" id="lmp" name="lmp" value="{{ $vitals->lmp }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="lsc">L.S.C:</label>
					    <input type="text" class="form-control" id="lsc" name="lsc" value="{{ $vitals->lsc }}">
					</div>
					<div class="form-group col-12 col-sm-4">
					    <label class="form-control-label" for="method">Method:</label>
					    <input type="text" class="form-control" id="method" name="method" value="{{ $vitals->method }}">
					</div>
				</div>	
				<div class="row">
					<div class="form-group col-12 col-sm-2">
						{{ csrf_field() }}
					    <button class="btn btn-info">Save</button>
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/vitalsign/index.blade.php
@extends('layouts.app')
@section('content') 
<div class="container mt-4">
    <div class="card card-info">
        <div class="card-header">
             Patients
        </div>
        <div class="card-body">
            @include('shared.alerts')
            <table class="table table-light table-bordered" id="myTable">
                <thead>
                    <th>ID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Date Created</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($patients as $patient)
                    <tr>
                        <td>{{ $patient->id }}</td>
                        <td>{{ $patient->firstname }}</td>
                        <td>{{ $patient->lastname }}</td>
                        <td>{{ $patient->created_at }}</td>
                        <td>
                            @if($patient->vitalsign->isEmpty())
                            <a href="{{ route('vitalsign.create',['id' => $patient->id]) }}" class="btn btn-sm btn-primary">New Record</a>
                            @else
                            <a href="{{ route('vitalsign.edit',['id' => $patient->id]) }}" class="btn btn-sm btn-primary text-light">Edit</a>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            A Total Patients of {{ $patients->count() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
    $('#myTable').DataTable();
</script>
@endpush
@push('styles')
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush