routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/','print_forms.chem');
// Route::redirect('/','login');
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('test',function(){
	return response()->json(['test'=>'test']);	
});

Auth::routes();
Route::resource('information','BasicInformationController')->except(['delete']);
Route::name('vitalsign.')->prefix('vitalsign/')->group(function(){
    Route::get('/','VitalSignController@index')->name('index');
	Route::get('create/{id}','VitalSignController@create')->name('create');
	Route::post('store/{id}','VitalSignController@store')->name('store');
	Route::get('edit/{id}','VitalSignController@edit')->name('edit');
	Route::patch('update/{id}','VitalSignController@update')->name('update');
});
Route::name('eyesight.')->prefix('eyesight/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::name('psychology.')->prefix('psychology/')->group(function(){
    Route::get('/','EyeSightController@index')->name('index');
	Route::get('create/{id}','EyeSightController@create')->name('create');
	Route::post('store/{id}','EyeSightController@store')->name('store');
	Route::get('edit/{id}','EyeSightController@edit')->name('edit');
	Route::patch('update/{id}','EyeSightController@update')->name('update');
});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('styles')
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    @if (Auth::guest())
                        <li class="nav-item"><a href="{{ route('login') }}" class="nav-link">Login</a></li>
                        <!--<li class="nav-item"><a href="{{ route('register') }}" class="nav-link">Register</a></li>-->
                    @else
                        @if(Auth::user()->role_id == '2')
                        <li class="nav-item {{ Nav::isResource('information',null,'active') }}">
                            <a href="{{ route('information.index') }}" class="nav-link">Patient</a>
                        </li>
                        @elseif(Auth::User()->role_id == '3')
                        <li class="nav-item {{ Nav::isResource('vitalsign',null,'active') }}">
                            <a href="{{ route('vitalsign.index') }}" class="nav-link">Patient</a>
                        </li>
                        @elseif(Auth::user()->role_id == '9')
                        <li class="nav-item {{ Nav::isResource('eyesight',null,'active') }}">
                            <a href="{{ route('eyesight.index') }}" class="nav-link">Patient</a>
                        </li>
                        @elseif(Auth::user()->role_id == '10')
                        <li class="nav-item {{ Nav::isResource('psychology',null,'active') }}">
                            <a href="{{ route('psychology.index') }}" class="nav-link">Patient</a>
                        </li>
                        @endif
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ Auth::user()->name }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a href="{{ route('logout') }}" class="dropdown-item"
                                   onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    @endif
                </ul>
            </div>

        </div>
    </nav>

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@stack('scripts')
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE HTML>
<html>
    <head>
        <title>@yield('title')</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        @yield('styles')
    </head>
    <body>
        @yield('content')
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
        @yield('scripts')
    </body>
</html>